version: "3.9"
services:
  cloud_service:
    build: .
    restart: on-failure
    ports:
      - "8080:8080"
    networks:
      - cloudnet
    environment:
        - spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
    depends_on:
        - postgres

  postgres:
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - storage-data:/var/lib/postgresql/data
    networks:
      - cloudnet
    ports:
      - "5432:5432"
networks:
  cloudnet:

volumes:
  storage-data: